# Copyright (C) 2020-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

NAME = ql-iob
SOURCES = ql-iob.cc pcf_parser.cc pinmap_parser.cc
include ../Makefile_plugin.common
