# The latch test is disabled as latches are not supported in the qlf_k4n8.

TESTS = dffs \
	iob_no_flatten \
	soft_adder \
	logic

include $(shell pwd)/../../Makefile_test.common

dffs_verify = true
iob_no_flatten_verify = true
latches_verify = true
soft_adder_verify = true
logic_verify = true
