TESTS = dffs \
	iob_no_flatten \
	latches \
	soft_adder \
	logic

include $(shell pwd)/../../Makefile_test.common

dffs_verify = true
iob_no_flatten_verify = true
latches_verify = true
soft_adder_verify = true
logic_verify = true
