# Copyright (C) 2020-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

NAME = dsp-ff
SOURCES = dsp_ff.cc 

include ../Makefile_plugin.common

install:
	install -D nexus-dsp_rules.txt $(DATA_DIR)/nexus/dsp_rules.txt

