# The latch test is disabled as latches are not supported in the qlf_k6n10.

TESTS = dffs \
	iob_no_flatten \
	latches \
	hard_adder \
	bram \
	logic

include $(shell pwd)/../../Makefile_test.common

dffs_verify = true
iob_no_flatten_verify = true
latches_verify = true
hard_adder_verify = true
bram_verify = false
logic_verify = true
