# Copyright (C) 2020-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

NAME = design_introspection
SOURCES = design_introspection.cc \
	  get_cmd.cc \
	  get_nets.cc \
	  get_ports.cc \
	  get_cells.cc \
	  get_pins.cc \
	  get_count.cc \
	  selection_to_tcl_list.cc

include ../Makefile_plugin.common
