# Copyright (C) 2019-2022 The SymbiFlow Authors
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

test:
	yosys -p "tcl script.tcl"
	touch ok

clean:
	rm -rf ok

.PHONY: test clean
