# Copyright (C) 2020-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

NAME = sdc
SOURCES = buffers.cc \
          clocks.cc \
          propagation.cc \
          sdc.cc \
          sdc_writer.cc \
          set_false_path.cc \
          set_max_delay.cc \
          set_clock_groups.cc
include ../Makefile_plugin.common
