# Copyright (C) 2020-2022  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

TESTS = \
    nexus_mult

include $(shell pwd)/../../Makefile_test.common

nexus_mult_verify = true
