# Copyright (C) 2019-2022 The SymbiFlow Authors
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

TESTS = \
    nexus_mult \
    nexus_mult_wide \
    nexus_fftypes \
    nexus_conn_conflict \
    nexus_conn_share \
    nexus_param_conflict

include $(shell pwd)/../../Makefile_test.common

nexus_mult_verify = true
nexus_mult_wide_verify = true
nexus_fftypes_verify = true
nexus_conn_conflict_verify = true
nexus_conn_share_verify = true
nexus_param_conflict_verify = true
