# Copyright (C) 2020-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

TESTS = fanout \
	hierarchy \
	multi_bit \
	single_bit \
	toplevel

include $(shell pwd)/../../Makefile_test.common

fanout_verify = true
hierarchy_verify = true
multi_bit_verify = true
single_bit_verify = true
toplevel_verify = true
