TESTS = fanout \
	hierarchy \
	multi_bit \
	single_bit \
	toplevel

include $(shell pwd)/../../Makefile_test.common

fanout_verify = true
hierarchy_verify = true
multi_bit_verify = true
single_bit_verify = true
toplevel_verify = true
